### ISSUE TITLE
Composer Update Can not find the repository

### ISSUE THREAD

**Issue by yah-ya** [sallar/laravel-jdate#2]
hi,i can't get this repository downloaded via composer.... this is what i get :

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package miladr/jalali could not be found in any version, the
re may be a typo in the package name.
  Problem 2
    - Installation request for laravel/framework 4.0.\* -> satisfiable by laravel
/framework[4.0.x-dev].
    - Removal request for laravel/framework == 4.0.9999999.9999999-dev

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your min
  imum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion f
  or more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common
 problems.

**Comment by sallar** [comment]
Hi,

This package is built for Laravel 3. Your version of Laravel is 4 which is not supported. Use this port instead: 
https://packagist.org/packages/miladr/jalali
